export const nameList = () => {
    return [
        "Ndiaye: Diatta, Ndiaye Maysa",
        "Diop: Jubba",
        "Ba: Pullo Jeeri",
        "Diallo: Jeeri",
        "Sow: Pullo Jeeri",
        "Diouf: Njoxobaay",
        "Gueye: Njooro",
        "Fall: Ndiaga Yaaram",
        "Faye: Biram",
        "Sarr",
        "Cisse: Ngaari, Mandimóori, Njar Meew",
        "Seck: Singanaar, Ndaanane",
        "Niang: Baalo",
        "Thiam: Baylo, Baabel, Demba Bookar",
        "Mbaye",
        "Sene: Caali",
        "Ka",
        "Dieng: Saala",
        "Diagne: Naar, Diagne Birame Diagne",
        "Balde",
        "Toure: Mandimóori",
        "Dia",
        "Sall: Ngaari",
        "Ngom",
        "Camara: Yille",
        "Ndao: SaaNdene",
        "Gaye: Masar",
        "Kane",
        "Drame",
        "Diatta",
        "Sane",
        "Lo: Ndaam",
        "Mbengue: Mboor",
        "Diaw: Fara",
        "Dione",
        "Sylla",
        "Samb",
        "Ndour: Waali Mbergaan",
        "Mane",
        "Diedhiou",
        "Ndoye: Maalimaram",
        "Diao",
        "Badji: Basen",
        "Seye: Yaaram",
        "Wade: Fara Saali Ngaari",
        "Ly",
        "Kebe",
        "Dieye: Masàmba ak Yerim",
        "Barry",
        "Mendy",
        "Sagna",
        "Tine",
        "Coly",
        "Keita",
        "Tall",
        "Thiaw: Maysa",
        "Ndong",
        "Mballo",
        "Diakhate",
        "Gning",
        "Badiane",
        "Deme",
        "Dieme",
        "Kande",
        "Seydi",
        "Traore",
        "Ciss",
        "Sakho",
        "Cissokho",
        "Beye",
        "Coulibaly",
        "Mboup: Jali",
        "Sambou",
        "Mbodji",
        "Pouye",
        "Diene",
        "Mbow",
        "Gomis",
        "Leye",
        "Loum",
        "Thioune: Demba Yacine Saakor",
        "Kante",
        "Sadio",
        "Sonko",
        "Niane",
        "Senghor",
        "Dabo",
        "Top",
        "Mbacke: Balla",
        "Sidibe",
        "Manga",
        "Ndione",
        "Boye",
        "Diarra",
        "Gassama",
        "Sabaly",
        "Goudiaby",
        "Faty",
        "Soumare",
        "Thiao",
        "Gningue",
        "Konte",
        "Niass: Kumba Abdalaa",
        "Ndaw",
        "Niasse: Kumba Abdalaa",
        "Guisse: Maabo",
        "Souare",
        "Diaby",
        "Konate",
        "Bodian",
        "Diawara",
        "Mbodj: Fara",
        "Aidara",
        "Kandji",
        "Gadiaga",
        "Diane",
        "Marone",
        "Boiro",
        "Biaye",
        "Fofana",
        "Diack",
        "Diome",
        "Diongue",
        "Anne",
        "Diba",
        "Dioum",
        "Aw",
        "Sambe",
        "Kamara: Yille",
        "Tamba",
        "Khouma",
        "Biteye",
        "Bakhoum",
        "Danfakha",
        "Diamanka",
        "Thioye",
        "Bassene",
        "Ndongo",
        "Samba",
        "Yade",
        "Dembele",
        "Kama: Waali",
        "Bousso: Baali",
        "Diame",
        "Hane",
        "Basse",
        "Barro",
        "Wane",
        "Kasse: Maabo",
        "Amar",
        "Deh",
        "Babou",
        "Ndir",
        "Mar",
        "Djitte",
        "Segnane",
        "Djiba",
        "Willane",
        "Danfa",
        "Syll",
        "Mangane",
        "Nguer",
        "Thiongane",
        "Lam",
        "Hanne",
        "Pene",
        "Thioub",
        "Bop",
        "Wilane",
        "Thior",
        "Vilane",
        "Demba",
        "Tounkara",
        "Diassy",
        "Bathily",
        "Thiare",
        "Mandiang",
        "Gano",
        "Diakhite",
        "Diawo",
        "Thiandoum",
        "Doucoure",
        "Kanoute",
        "Tendeng",
        "Bah",
        "Sagne",
        "Djigo",
        "Bayo",
        "Daffe",
        "Wagne",
        "Correa",
        "Sock",
        "Mansaly",
        "Diasse",
        "Khoule",
        "Kone",
        "Diankha",
        "Tambedou",
        "Souane",
        "Bindia",
        "Konteye",
        "Diakite",
        "Youm",
        "Preira",
        "Cissoko",
        "Mbathie",
        "Thiombane",
        "Doumbouya",
        "Gadio",
        "Pam",
        "Kounta",
        "Samoura",
        "Bocoum",
        "Talla",
        "Thiane",
        "Kouyate",
        "Dansokho",
        "Kaire",
        "Sour",
        "Wone",
        "Siby",
        "Bodiang",
        "Sankhare",
        "Diom",
        "Diakhaby",
        "Diouck",
        "Sokhna",
        "Sao",
        "Marena",
        "Bane",
        "Watt",
        "Gadjigo",
        "Ndom",
        "Sine",
        "Nguirane",
        "Ndior",
        "Ndiour",
        "Diabang",
        "Dasylva",
        "Ndecky",
        "Der",
        "Sougou",
        "So",
        "Diabaye",
        "Thiall",
        "Fam",
        "Diol",
        "Ndiongue",
        "Koulibaly",
        "Gakou",
        "Dicko",
        "Guene",
        "Hann",
        "Sadiakhou",
        "Diong",
        "Diakhoumpa",
        "Ndome",
        "Wague",
        "Boubane",
        "Diaite",
        "Sogue",
        "Biagui",
        "Câmara",
        "Salane",
        "Ball",
        "Diadhiou",
        "Fedior",
        "Wele",
        "Sangare",
        "Sam",
        "Koita",
        "Kote",
        "Ndiouck",
        "Athie",
        "Macalou",
        "Koume",
        "Sissokho",
        "Daff",
        "Kaba",
        "Doumbia",
        "Nguette",
        "Sembene",
        "Yatte",
        "Dioh",
        "Kare",
        "Diambang",
        "Savane",
        "Niassy",
        "Diandy",
        "Diokhane",
        "Mara",
        "Sano",
        "Niabaly",
        "Oualy",
        "Tamboura",
        "Solly",
        "Diattara",
        "Sylva",
        "Massaly",
        "Sy: Sawaane",
        "Waly: Badiane"
    ].sort(function(a, b){
        if(a < b) { return -1; }
        if(a > b) { return 1; }
        return 0;
    })
}
