import {fetchDakkantalData} from "../store/dynamo";

export const nameList = () => {
    fetchDakkantalData()
    return [
        "Agne: Tamboura",
        "Aïdara: Karaaraa",
        "Amar: Dikké",
        "Anne: Gaano Dimo",
        "Athie: Baalo",
        "Aw",
        "Ba: Poullo Jeeri, Labaado",
        "Babou: Maïssa Tamaram, Maïssa Arviz Zouwayei",
        "Badiane: Sanou, Sakoura Waly",
        "Badji: Bassene, Foro, Nafa",
        "Bah: Poullo Jeeri, Labaado",
        "Bakayoko: Bakha Kounkou, Bakha Niénié",
        "Bakhoum: Ndondol, Galombe",
        "Baldé: Bolon",
        "Ball",
        "Bane",
        "Barro: Manaasi",
        "Barry: Poulo, Seydi",
        "Basse: Elimane Amré, Malamine",
        "Bassene",
        "Bathily: Simpera",
        "Bayo: Sora",
        "Bèye: Ndiogou",
        "Biagui",
        "Biaye: Tambana Niassou",
        "Bindia",
        "Biteye",
        "Bocoum: Mouradou Ciré",
        "Bodian: Diang Diary",
        "Boiro: Galo",
        "Bop",
        "Boubane",
        "Bousso: Baali",
        "Boye: Mara",
        "Camara: Yille",
        "Câmara: Yille",
        "Ciss",
        "Cisse: Ngaari, Mandimóori, Njar Meew",
        "Cissokho",
        "Cissoko",
        "Coly: Dioumaré Mansa",
        "Correa",
        "Coulibaly: Faal, Mansassi",
        "Dabo: Dioula, Sanka",
        "Daff: Daraméré",
        "Daffé: Diao Niarkan Banna",
        "Dahaba: Simaa",
        "Damaré: Mousso",
        "Danfa",
        "Danfakha",
        "Dansokho",
        "Dasylva",
        "Deh",
        "Demba",
        "Dembele",
        "Dème: Dioba Sylla",
        "Der",
        "Derneville: Ma thia Paris Colo Samba ma dess Mbao",
        "Dia: Pullo",
        "Diabang: Marry",
        "Diabaye",
        "Diabong: Sadougoupe",
        "Diaby",
        "Diack",
        "Diadhiou",
        "Diagne: Naar, Diagne Birame Diagne, Mataari Mbaye",
        "Diagoura: Tambacoly",
        "Diaite",
        "Diakhaby",
        "Diakhaté: kaba Yéri",
        "Diakhite",
        "Diakhoumpa: Niaana",
        "Diakite",
        "Dial: Jeeri",
        "Diallo: Jeeri",
        "Diamanka: Soriang",
        "Diambang",
        "Diamé: Djilankaa, Moussa",
        "Diandy",
        "Diane",
        "Diankha",
        "Diao: Banna",
        "Diarra: Kolo Bakary",
        "Diasse: Al Diasse Mamour Ndiaye Dorobe, Biram Dieum Ngoy Thiam, Ngoy Thiam Ndiougour Thiam Ale Demba ma Yoro Bator Thiam",
        "Diassy",
        "Diatta: Ndiaye",
        "Diattara",
        "Diaw: Fara",
        "Diawara: Dicko",
        "Diawo",
        "Diba",
        "Dicko",
        "Diedhiou: Bouré",
        "Diemé: Djilankaa, Moussa, Mansa Mary",
        "Diene: Ndióogu",
        "Diene",
        "Dieng: Saala, Diossi, Mbella, Wèyndé",
        "Dieye: Diogo Boury, Masàmba ak Yerim, Gandjol, Mataalibé",
        "Dioh",
        "Diokhane",
        "Diol",
        "Diom: Dioma Abou",
        "Dione: Maïssa Waly, Woulla",
        "Diong",
        "Diongue: Dieri",
        "Diop: Jóoba Jubba",
        "Diouck: Maïssa Alima Fadaan",
        "Diouf: Njoxobaay, Matiou Lam Sedar",
        "Dioum",
        "Djiba",
        "Djigal: Boubou Demba",
        "Djigo",
        "Djitte",
        "Doucoure",
        "Doumbia",
        "Doumbouya",
        "Drame: Kandjé Socé, Kandji Mori",
        "Faal: Mathioro Faye, Njaga Yaaram",
        "Fam",
        "Faty",
        "Faye: Biram Penda Waagaan",
        "Fedior",
        "Fofana",
        "Gackou: Siméri, Tawda",
        "Gadiaga",
        "Gadio: Amadi Ma-Socé Ramata, Demba",
        "Gadjigo",
        "Gakou",
        "Gangué: Sow",
        "Gano",
        "Gassama: Diaby",
        "Gaye: Masar, Mol",
        "Gning: Diabo",
        "Gningue",
        "Gomis: Agagnar",
        "Gomis",
        "Goudiaby: Samaté",
        "Guene",
        "Gueye: Njooro, Ndiora Bassi",
        "Guindo: Ogo Togo",
        "Guisse: Maabo",
        "Hane",
        "Hann",
        "Hanne",
        "Ka: Ardo",
        "Kaba",
        "Kabe: Maaboury",
        "Kaire",
        "Kaloga: Naabou ",
        "Kama: Waali",
        "Kamara: Yille",
        "Kande: Barry",
        "Kandji: Socé",
        "Kane: Diallo",
        "Kanoute",
        "Kante",
        "Kare",
        "Kasse: Maabo",
        "Kébé: Ndiouga Alé Moussé, Djinka",
        "Keita: Mansarein, Mandimory",
        "Keneme:  Coumba Diéry, Mabo",
        "Khoule",
        "Khouma: Mandimory",
        "Koita",
        "Koma: Dary",
        "Konate",
        "Kondjira: Tambalaye",
        "Kone",
        "Konté: Dioula",
        "Konteye",
        "Kote",
        "Koulibaly",
        "Koume",
        "Kounta",
        "Kouyate",
        "Labou: Ndjingué",
        "Lam: Meïssa Bara, Demba Gadial",
        "Leye: Bousso Ndiamé",
        "Lo: Ndaam",
        "Loum: Ndéné, Nianté, Coly Djimare",
        "Ly: Bousso kangué Torobé",
        "Maal: Demba",
        "Macalou",
        "Mandiang",
        "Mané: Djonkéléfa, Waly, Nianthio",
        "Manga: Mansaly, Badiane",
        "Mangane",
        "Mansal: Manga",
        "Mansaly",
        "Mar: Gora, Mar a Mousso",
        "Mara: Biram",
        "Marena",
        "Marone",
        "Massaly",
        "Mbacké: Bala, Baari, Xéwar, Dimb",
        "Mballo: Bana",
        "Mbathie",
        "Mbaye: Mbasou, Ali Samb, Mbaxar, Yaaram, Madiaga Meïssa Dior",
        "Mbengue: Mboor, Singar",
        "Mbodj: Fara",
        "Mbodji",
        "Mboup: Mbouba Dialy, Dial, Mbaxata, Badialy, Youga Mbissane",
        "Mbow: Ngaala Wude",
        "Mediang: Kathiaky",
        "Mendy",
        "Missirah: Mame Balla",
        "Nam: Médoune Fara",
        "Ndao: SaaNdene",
        "Ndaw: Kounda, Belleup Boroom Ndoukoumane",
        "Ndecky",
        "Ndialde: Coumba",
        "Ndiaye: Jaata, Gaïndé, Massoogui, Maysa",
        "Ndione: Kana",
        "Ndiongue",
        "Ndior",
        "Ndiouck",
        "Ndiour",
        "Ndir",
        "Ndjim: Doualé",
        "Ndom",
        "Ndome",
        "Ndong: Massa",
        "Ndongo",
        "Ndour: Ndoura Waly",
        "Ndour: Waali Mbergaan",
        "Ndoye: Maalimaram, Lebu",
        "Ngom: Fassar",
        "Nguer",
        "Nguette",
        "Nguiraan: Demba Lem",
        "Nguirane",
        "Niabaly",
        "Niakh: Niakhoula Mboudaye*",
        "Niane: Samba Dicko",
        "Niang: Baalo",
        "Niass: Kumba Abdalaa",
        "Niasse: Kumba Abdalaa",
        "Niassy",
        "Oualy",
        "Pam",
        "Pene",
        "Pouye: Tilasse Siga, Mbissane",
        "Preira: Gagna",
        "Preira",
        "Sabaly: Bodian",
        "Sadiakhou",
        "Sadio: Soumaré",
        "Sadio",
        "Sagna: Ndóobaa",
        "Sagne",
        "Sakho: Wahané, Djombéra, Biiba, Elimane, Mandy Mory",
        "Salane",
        "Sall: Ngaari, Baalo",
        "Sam: Gatti Laabo",
        "Samassa Yéra",
        "Samaté: Goudjaby",
        "Samb: Amar Demba, Diogal, Makhari",
        "Samb: Ndiogou, Mbakharame, Joogal",
        "Samba",
        "Sambe",
        "Sambou: Diarra",
        "Samoura",
        "Sanding: Tianna",
        "Sané: Balaama",
        "Sangare",
        "Sangharé: Barri Poulo",
        "Sanghott: Sangou Lélél",
        "Sankhare",
        "Sano",
        "Sanokho: Doucara",
        "Sao",
        "Sarr: Mboundou, Dioula, Gueleem",
        "Sarr",
        "Sarré: Maabo",
        "Savane",
        "Seck: Singanaar, Ndaanane",
        "Segnane",
        "Sembene",
        "Sène: Thiaali, Massene, Saamane",
        "Senghor: Mady",
        "Seydi: Sall",
        "Seye: Baaba, Ngary, Maïssa",
        "Seye: Yaaram",
        "Siby: Dierinké",
        "Sidibe",
        "Signaté: Dioula",
        "Sine",
        "Sissokho: Banna, Sora",
        "So",
        "Sock",
        "Sogue",
        "Sokhna",
        "Solly",
        "Soly: Silaty",
        "Sonko: Yaabo",
        "Souané: Jomaye",
        "Souaré: Bour NGalam, Sambahé",
        "Sougou: Fara",
        "Soumaré: Bour Ngalam",
        "Sour",
        "Sow: Pullo Jéeri",
        "Sy: Malick, Demba, Sawaandé",
        "Syll",
        "Sylla: Matar, Fabakheira, Diaby, Makhaneira, Nimisseera, Ngary",
        "Sylva",
        "Tall: Guédé",
        "Talla: koore Naadio",
        "Tamba",
        "Tambédou: Khoudieye Makha",
        "Tamboura",
        "Tandian: Mory",
        "Tandjigora: Diako Siré",
        "Tendeng",
        "Teuw: Gora",
        "Thiall",
        "Thiam: Demba Bookar, Demba lém, Baïlo, Baabel",
        "Thiandoum: Ngoné yayi Ngane",
        "Thiané: Marena, Kémédjoula*",
        "Thiao",
        "Thiare",
        "Thiaw: Maysa",
        "Thiombane",
        "Thiongane",
        "Thior",
        "Thioub",
        "Thioune: Alpha, Demba Yacine Saakor",
        "Thioye: Ndiaga Massa",
        "Tine: Maïssa Fegane",
        "Togola: Ndiaye",
        "Top",
        "Tounkara: Guira",
        "Toure: Mandimóori",
        "Traoré: Diop, Tiranmakha Sy",
        "Vilane",
        "Wade: Fara Saali Ngaari, Fari Ndiack",
        "Wagne",
        "Wagué: Diakhawourou Baaba Kissimare",
        "Waly: Badiane, Birom Banna",
        "Wañaan: Njaga Samba",
        "Wane: Mboumba",
        "War: Galo Toucouleur",
        "Warro: Ndéné",
        "Watt",
        "Wélé: Diallo, Diao",
        "Wilane: Mody",
        "Wone: Thiofi",
        "Yade: Baay Gillaay",
        "Yague: Massamba, Masseye, Bakh, Bawoul Dara",
        "Yatt: Gnoxo Coumba, SambaDiaaga",
        "Yatte",
        "Youm: Codoum Dialaw, Mandéla"
    ].sort(function(a, b){
        if(a < b) { return -1; }
        if(a > b) { return 1; }
        return 0;
    }).map((item, i) => ({
        id: i,
        name: item.split(':')[0],
        dakkantal: item.split(':').length > 1 ? item.split(':')[1] : '',
    }))
}
